export const OPENING_REPORT_TOTAL_SECTIONS = 6;

export const SSE_HEARTBEAT_INTERVAL_MS = 15_000;

export const SECTION_PROGRESS_EMIT_INTERVAL_MS = 500;

export const GENERATION_CONCURRENCY_WINDOW_MS = 5 * 60 * 1000;

export const DEFAULT_SECTION_TEMPERATURE = 0.7;

export const DEFAULT_SECTION_MAX_TOKENS = 3000;
