export const OUTLINE_DEFAULT_MAX_DEPTH = 3;
export const OUTLINE_MAX_DEPTH_LIMIT = 4;

export const OUTLINE_GENERATION_WORDCOUNT_MIN_RATIO = 0.9;
export const OUTLINE_GENERATION_WORDCOUNT_MAX_RATIO = 1.1;

export const OUTLINE_LOCK_WORDCOUNT_MIN_RATIO = 0.85;
export const OUTLINE_LOCK_WORDCOUNT_MAX_RATIO = 1.15;

export const OUTLINE_PATH_SEGMENT_PAD = 4;

export const OUTLINE_MIN_CHAPTERS = 4;
export const OUTLINE_MAX_CHAPTERS = 8;
