export const LLM_ERROR_CODES = {
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  LLM_RATE_LIMIT: 'LLM_RATE_LIMIT',
  LLM_INVALID_RESPONSE: 'LLM_INVALID_RESPONSE',
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  LLM_JSON_PARSE_FAILED: 'LLM_JSON_PARSE_FAILED',
  LLM_QUOTA_EXCEEDED: 'LLM_QUOTA_EXCEEDED',
} as const;

export type LlmErrorCode =
  (typeof LLM_ERROR_CODES)[keyof typeof LLM_ERROR_CODES];
